"""Tier 2.1b — `episteme check new <name>` scaffolder.

Generates a minimal, working PreToolUse check from a vendored template
into ``examples/checks/<name>.py`` (or a user-specified path). Three
template shapes mirror the canonical examples shipped in Event 110
sub-phase 2.1:

- ``block``    — refuse a tool call on pattern match (block_rmrf shape)
- ``advisory`` — write to stderr, exit 0 (flag_kernel_edits shape)
- ``surface``  — read .episteme/reasoning-surface.json, refuse on field
  gap (require_disconfirmation_for_irreversible shape)

The scaffolder closes Finding F4 from
``docs/PRIVATE_ANALYSIS_PI_VS_EPISTEME.md`` (check-authoring threshold)
by reducing required reading from 5 kernel docs to a single template +
the one-liner edit on the regex / path / blueprint field the contributor
cares about.

The scaffolder does NOT register the new check into the live PreToolUse
hook chain. The user opts in by editing their own
``~/.claude/settings.json`` (or ``.claude/settings.json``). The kernel's
authority comes from the operator choosing what enforces what.
"""
from __future__ import annotations

import re
from pathlib import Path

NAME_RE = re.compile(r"^[a-z0-9][a-z0-9_-]{0,63}$")
TEMPLATE_TYPES = ("block", "advisory", "surface")


_BLOCK_TEMPLATE = '''#!/usr/bin/env python3
"""{name_human} — block tool calls matching {pattern_description}.

Generated by `episteme check new {name} --type=block`.

The minimum-viable check shape: read JSON from stdin, pattern-match
on tool_input.command, exit 2 with stderr message on match.

Wire into ~/.claude/settings.json (matcher: "Bash"):

  {{"type": "command", "command": "python3 /abs/path/to/{name}.py"}}

See examples/checks/README.md for the full check contract.
"""
import json
import re
import sys

# TODO: edit this pattern to match the shape you want to refuse.
PATTERN = re.compile(r"\\bdangerous-pattern\\b")


def main() -> int:
    try:
        payload = json.loads(sys.stdin.read() or "{{}}")
    except json.JSONDecodeError:
        return 0  # malformed payload: don't block
    command = (payload.get("tool_input") or {{}}).get("command", "")
    if PATTERN.search(command):
        sys.stderr.write(
            "[{name}] Refused: pattern match.\\n"
            f"  command: {{command}}\\n"
            "  to override: rewrite the command, or temporarily remove this hook from settings.json.\\n"
        )
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


_ADVISORY_TEMPLATE = '''#!/usr/bin/env python3
"""{name_human} — advisory warning on {pattern_description}.

Generated by `episteme check new {name} --type=advisory`.

Demonstrates the advisory-not-block pattern: write to stderr, exit 0.
The agent sees the message and can act on it; the call proceeds.

Wire into ~/.claude/settings.json (matcher: "Edit|Write|MultiEdit"):

  {{"type": "command", "command": "python3 /abs/path/to/{name}.py"}}

See examples/checks/README.md for the full check contract.
"""
import json
import sys

# TODO: edit these prefixes to match the paths you want to flag.
PROTECTED_PREFIXES = (
    "path/you/care/about/",
)


def _extract_path(payload: dict) -> str:
    tool_input = payload.get("tool_input") or {{}}
    if isinstance(tool_input, dict):
        return tool_input.get("file_path", "") or ""
    return ""


def main() -> int:
    try:
        payload = json.loads(sys.stdin.read() or "{{}}")
    except json.JSONDecodeError:
        return 0
    path = _extract_path(payload)
    if not path:
        return 0
    if not any(prefix in path for prefix in PROTECTED_PREFIXES):
        return 0
    sys.stderr.write(
        "[{name}] Advisory: editing surface flagged by this check.\\n"
        f"  path: {{path}}\\n"
        "  this check is advisory only — the edit will proceed. Override silently by removing\\n"
        "  this hook from settings.json, or upgrade to a blocking variant by changing the exit code.\\n"
    )
    return 0  # advisory only — do not block


if __name__ == "__main__":
    raise SystemExit(main())
'''


_SURFACE_TEMPLATE = '''#!/usr/bin/env python3
"""{name_human} — refuse {pattern_description} when the Reasoning Surface
lacks {surface_field}.

Generated by `episteme check new {name} --type=surface`.

Demonstrates the surface-aware check pattern: a check can read
.episteme/reasoning-surface.json from cwd, inspect operator-declared
fields, and decide based on epistemic state rather than just command shape.

Wire into ~/.claude/settings.json (matcher: "Bash"):

  {{"type": "command", "command": "python3 /abs/path/to/{name}.py"}}

See examples/checks/README.md for the full check contract.
"""
import json
import re
import sys
from pathlib import Path

# TODO: edit these patterns to match the commands you want to gate.
GATED_PATTERNS = [
    re.compile(r"\\byour-gated-command\\b"),
]

# TODO: change this to the surface field you want to require.
REQUIRED_SURFACE_FIELD = "{surface_field}"
MIN_FIELD_LEN = 15
LAZY_VALUES = {{"", "n/a", "none", "tbd", "todo", "해당 없음", "없음"}}

SURFACE_PATH = Path.cwd() / ".episteme" / "reasoning-surface.json"


def _surface_field_status() -> tuple[bool, str]:
    if not SURFACE_PATH.exists():
        return False, f"no surface at {{SURFACE_PATH}}"
    try:
        surface = json.loads(SURFACE_PATH.read_text())
    except json.JSONDecodeError as e:
        return False, f"surface unparseable: {{e}}"
    raw = surface.get(REQUIRED_SURFACE_FIELD)
    value = (raw or "").strip()
    if value.lower() in LAZY_VALUES:
        return False, f"{{REQUIRED_SURFACE_FIELD}} is empty or lazy ({{value!r}})"
    if len(value) < MIN_FIELD_LEN:
        return False, f"{{REQUIRED_SURFACE_FIELD}} too short ({{len(value)}} chars; need >= {{MIN_FIELD_LEN}})"
    return True, ""


def main() -> int:
    try:
        payload = json.loads(sys.stdin.read() or "{{}}")
    except json.JSONDecodeError:
        return 0
    command = (payload.get("tool_input") or {{}}).get("command", "")
    if not any(p.search(command) for p in GATED_PATTERNS):
        return 0
    ok, reason = _surface_field_status()
    if ok:
        return 0
    sys.stderr.write(
        "[{name}] Refused: gated op without {surface_field}.\\n"
        f"  command: {{command}}\\n"
        f"  reason:  {{reason}}\\n"
        f"  to proceed: declare {{REQUIRED_SURFACE_FIELD}} in {{SURFACE_PATH}}\\n"
    )
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
'''


_TEMPLATES: dict[str, str] = {
    "block": _BLOCK_TEMPLATE,
    "advisory": _ADVISORY_TEMPLATE,
    "surface": _SURFACE_TEMPLATE,
}


_PATTERN_DESCRIPTIONS: dict[str, str] = {
    "block": "the dangerous shape you care about",
    "advisory": "the surface you want to flag",
    "surface": "the gated command class",
}


_TEMPLATE_HELP_LINES: tuple[tuple[str, str], ...] = (
    ("block",    "refuse a tool call on pattern match (block_rmrf shape)"),
    ("advisory", "write to stderr, exit 0 (flag_kernel_edits shape)"),
    ("surface",  "read .episteme/reasoning-surface.json, refuse on field gap"),
)


class CheckNewError(Exception):
    """Raised on any user-facing scaffolder error (invalid name, file
    exists without --force, unknown template type)."""


def validate_name(name: str) -> None:
    if not isinstance(name, str) or not NAME_RE.match(name):
        raise CheckNewError(
            f"invalid check name: {name!r}. Names must match "
            f"{NAME_RE.pattern!r} (kebab-case alphanumeric, max 64 chars, "
            f"starts with letter or digit)."
        )


def render_template(name: str, type_: str = "block") -> str:
    if type_ not in _TEMPLATES:
        raise CheckNewError(
            f"unknown template type {type_!r}. Available: "
            f"{', '.join(TEMPLATE_TYPES)}."
        )
    template = _TEMPLATES[type_]
    name_human = name.replace("-", " ").replace("_", " ").title()
    surface_field = "disconfirmation" if type_ == "surface" else ""
    return template.format(
        name=name,
        name_human=name_human,
        pattern_description=_PATTERN_DESCRIPTIONS[type_],
        surface_field=surface_field,
    )


def scaffold_check(
    name: str,
    type_: str = "block",
    output: Path | None = None,
    project_root: Path | None = None,
    force: bool = False,
) -> Path:
    """Render the template and write the file. Returns the absolute path
    written. Raises CheckNewError on any user-facing failure."""
    validate_name(name)
    if type_ not in _TEMPLATES:
        raise CheckNewError(
            f"unknown template type {type_!r}. Available: "
            f"{', '.join(TEMPLATE_TYPES)}."
        )
    if output is None:
        root = project_root or Path.cwd()
        output = root / "examples" / "checks" / f"{name}.py"
    output = Path(output).resolve()
    if output.exists() and not force:
        raise CheckNewError(
            f"target already exists: {output}. Pass --force to overwrite."
        )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_template(name, type_))
    output.chmod(0o755)
    return output


def list_templates() -> str:
    """Return a human-readable description of available templates."""
    return "\n".join(
        f"  {t:<10} — {desc}"
        for t, desc in _TEMPLATE_HELP_LINES
    )
