from __future__ import annotations

import argparse
import json
import os
import platform
import re
import shutil
import subprocess
import sys
from datetime import date
from pathlib import Path
from typing import Iterable


REPO_ROOT = Path(__file__).resolve().parents[2]
HOME = Path.home()
CONDA_ROOT = Path(os.environ.get("AGENT_OS_CONDA_ROOT", str(HOME / "miniconda3")))
EXPECTED_BASE_PREFIX = str(CONDA_ROOT)
RUNTIME_MANIFEST = json.loads((REPO_ROOT / "core" / "runtime_manifest.json").read_text(encoding="utf-8"))


def _run(
    args: list[str],
    *,
    check: bool = True,
    capture_output: bool = True,
    cwd: Path | None = None,
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        args,
        check=check,
        text=True,
        capture_output=capture_output,
        cwd=str(cwd) if cwd else None,
    )


def _command_exists(name: str) -> bool:
    return shutil.which(name) is not None


def _write_text(path: Path, content: str, *, executable: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if existing == content:
            if executable:
                path.chmod(path.stat().st_mode | 0o111)
            return
    path.write_text(content, encoding="utf-8")
    if executable:
        path.chmod(path.stat().st_mode | 0o111)


def _copy_file(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


def _copy_tree(src: Path, dst: Path) -> None:
    for file_path in src.rglob("*"):
        if file_path.is_dir():
            continue
        rel = file_path.relative_to(src)
        _copy_file(file_path, dst / rel)


def _replace_tokens(content: str, mapping: dict[str, str]) -> str:
    rendered = content
    for key, value in mapping.items():
        rendered = rendered.replace(f"{{{{{key}}}}}", value)
    return rendered


def _today() -> str:
    return date.today().isoformat()


def _sysctl(name: str) -> str:
    try:
        return _run(["sysctl", "-n", name]).stdout.strip()
    except subprocess.CalledProcessError:
        return "unknown"


def _sw_vers(flag: str) -> str:
    try:
        return _run(["sw_vers", flag]).stdout.strip()
    except subprocess.CalledProcessError:
        return "unknown"


def _machine_context() -> dict[str, str]:
    mem_bytes = _sysctl("hw.memsize")
    mem_gb = "unknown"
    if mem_bytes.isdigit():
        mem_gb = str(int(mem_bytes) // 1024 // 1024 // 1024)
    return {
        "DATE": _today(),
        "HOME_PATH": str(HOME),
        "CONDA_ROOT": str(CONDA_ROOT),
        "OS_VERSION": _sw_vers("-productVersion"),
        "OS_BUILD": _sw_vers("-buildVersion"),
        "CPU": _sysctl("machdep.cpu.brand_string"),
        "MEM_GB": mem_gb,
        "ARCH": platform.machine(),
        "SHELL": os.environ.get("SHELL", "unknown"),
        "CLAUDE_VERSION": _tool_version(["claude", "--version"]),
        "CURSOR_VERSION": _tool_version(["cursor", "--version"], first_line=True),
        "GIT_VERSION": _tool_version(["git", "--version"]),
        "NODE_VERSION": _tool_version(["node", "-v"]),
        "NPM_VERSION": _tool_version(["npm", "-v"]),
        "PYTHON_POLICY": f"All local Python-backed agent-os commands run in Conda base at {CONDA_ROOT}.",
    }


def _tool_version(cmd: list[str], *, first_line: bool = False) -> str:
    try:
        output = _run(cmd).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "not installed"
    if first_line:
        return output.splitlines()[0] if output else "unknown"
    return output or "unknown"


def _load_template(rel_path: str) -> str:
    return (REPO_ROOT / "templates" / "project" / rel_path).read_text(encoding="utf-8")


def _managed_skills() -> list[Path]:
    selected = set(RUNTIME_MANIFEST["vendor_skills"] + RUNTIME_MANIFEST["custom_skills"])
    candidates = list((REPO_ROOT / "skills" / "vendor").glob("*/SKILL.md")) + list(
        (REPO_ROOT / "skills" / "custom").glob("*/SKILL.md")
    )
    skill_dirs: list[Path] = []
    for skill_file in candidates:
        skill_dir = skill_file.parent
        if skill_dir.name in selected:
            skill_dirs.append(skill_dir)
    return sorted(skill_dirs, key=lambda p: p.name)


def _resolve_memory_file(name: str) -> Path:
    """Return the personal file if it exists, else fall back to the example."""
    personal = REPO_ROOT / "core" / "memory" / "global" / f"{name}.md"
    if personal.exists():
        return personal
    return REPO_ROOT / "core" / "memory" / "global" / f"{name}.example.md"


def _render_user_claude_md() -> str:
    imports = "\n".join(
        f"@{_resolve_memory_file(name)}"
        for name in ["overview", "operator_profile", "workflow_policy", "python_runtime_policy"]
    )
    return (
        "# Agent OS Global Memory\n\n"
        "This file is generated by `agent-os sync`.\n"
        "Edit the source of truth in `~/agent-os/core/memory/global/`.\n\n"
        f"{imports}\n"
    )


def _init_memory() -> int:
    """Bootstrap personal memory files from *.example.md templates."""
    memory_dir = REPO_ROOT / "core" / "memory" / "global"
    names = ["overview", "operator_profile", "workflow_policy", "python_runtime_policy"]

    created: list[str] = []
    skipped: list[str] = []

    for name in names:
        personal = memory_dir / f"{name}.md"
        example = memory_dir / f"{name}.example.md"
        if personal.exists():
            skipped.append(f"{name}.md")
            continue
        if not example.exists():
            print(f"Warning: {name}.example.md not found, skipping.", file=sys.stderr)
            continue
        shutil.copy2(example, personal)
        created.append(f"{name}.md")

    if created:
        print("Created personal memory files:")
        for f in created:
            print(f"  core/memory/global/{f}")
        print("\nEdit these files with your personal context, then run `agent-os sync`.")
    if skipped:
        print(f"Already present (not overwritten): {', '.join(skipped)}")
    if not created and not skipped:
        print("Nothing to do.")
    return 0


def _agent_os_settings() -> dict:
    hooks_dir = REPO_ROOT / "core" / "hooks"
    py = f"{CONDA_ROOT}/bin/python"

    def hook_cmd(script: str, *, async_: bool = False) -> dict:
        h: dict = {"type": "command", "command": f"{py} {hooks_dir / script}"}
        if async_:
            h["async"] = True
        return h

    checkpoint_cmd = f"{py} {hooks_dir / 'checkpoint.py'}"

    return {
        "permissions": {
            "deny": [
                "Read(./.env)",
                "Read(./.env.*)",
                "Read(./secrets/**)",
                "Read(./**/*.pem)",
                "Read(./**/*.key)",
                "Read(./**/.npmrc)",
            ]
        },
        "hooks": {
            "SessionStart": [
                {"hooks": [hook_cmd("session_context.py")]}
            ],
            "PreToolUse": [
                {
                    "matcher": "Bash",
                    "hooks": [hook_cmd("block_dangerous.py")],
                }
            ],
            "PostToolUse": [
                {
                    "matcher": "Write|Edit|MultiEdit",
                    "hooks": [hook_cmd("format.py", async_=True)],
                },
                {
                    "matcher": "Write|Edit|MultiEdit",
                    "hooks": [hook_cmd("test_runner.py")],
                },
            ],
            "PermissionRequest": [
                {
                    "matcher": "Read|Glob|Grep",
                    "hooks": [{"type": "command", "command": "echo '{\"decision\":\"allow\"}'"}],
                }
            ],
            "PreCompact": [
                {"hooks": [hook_cmd("precompact_backup.py", async_=True)]}
            ],
            "Stop": [
                {"hooks": [hook_cmd("quality_gate.py")]},
                {"hooks": [{"type": "command", "command": checkpoint_cmd}]},
            ],
            "SubagentStop": [
                {"hooks": [{"type": "command", "command": checkpoint_cmd}]}
            ],
        },
    }


def _merge_claude_settings(existing: dict, agent_os: dict) -> dict:
    """Merge agent_os settings into existing without removing anything.

    - permissions.deny: union (no duplicates)
    - hooks.<event>: append agent-os entries whose commands aren't already present
    - All other existing keys: preserved untouched
    """
    import copy
    merged = copy.deepcopy(existing)

    # Merge deny rules
    deny = merged.setdefault("permissions", {}).setdefault("deny", [])
    for rule in agent_os.get("permissions", {}).get("deny", []):
        if rule not in deny:
            deny.append(rule)

    # Merge hooks — ensure each agent-os command is registered exactly once
    for event, entries in agent_os.get("hooks", {}).items():
        existing_entries = merged.setdefault("hooks", {}).setdefault(event, [])
        # Collect all commands already registered for this event
        registered_cmds: set[str] = set()
        for entry in existing_entries:
            for h in entry.get("hooks", []):
                registered_cmds.add(h.get("command", ""))
        for entry in entries:
            new_cmds = {h.get("command", "") for h in entry.get("hooks", [])}
            if not new_cmds.issubset(registered_cmds):
                existing_entries.append(entry)

    return merged


def _bootstrap_project(project_root: Path) -> None:
    project_root.mkdir(parents=True, exist_ok=True)
    mapping = _machine_context()
    mapping["PROJECT_ROOT"] = str(project_root)

    template_files = [
        "AGENTS.md",
        "CLAUDE.md",
        "docs/REQUIREMENTS.md",
        "docs/PLAN.md",
        "docs/PROGRESS.md",
        "docs/RUN_CONTEXT.md",
        "docs/NEXT_STEPS.md",
        ".claude/settings.json",
    ]
    created: list[str] = []
    preserved: list[str] = []
    for rel_path in template_files:
        target = project_root / rel_path
        if target.exists():
            preserved.append(rel_path)
            continue
        content = _replace_tokens(_load_template(rel_path), mapping)
        _write_text(target, content)
        created.append(rel_path)

    settings_local = project_root / ".claude" / "settings.local.json"
    if not settings_local.exists():
        _write_text(settings_local, "{}\n")
        created.append(".claude/settings.local.json")

    gitignore_path = project_root / ".gitignore"
    ignore_line = ".claude/settings.local.json"
    if gitignore_path.exists():
        current = gitignore_path.read_text(encoding="utf-8")
        if ignore_line not in current.splitlines():
            extra = current + ("\n" if not current.endswith("\n") else "") + ignore_line + "\n"
            _write_text(gitignore_path, extra)
    else:
        _write_text(gitignore_path, ignore_line + "\n")
        created.append(".gitignore")

    print(f"Bootstrapped project scaffold in {project_root}")
    if created:
        print("Created:")
        for item in created:
            print(f"  - {item}")
    if preserved:
        print("Preserved existing:")
        for item in preserved:
            print(f"  - {item}")


def _sync_user_runtime() -> None:
    claude_root = HOME / ".claude"
    cursor_root = HOME / ".cursor" / "skills"
    codex_root = HOME / ".codex" / "skills"

    _write_text(claude_root / "CLAUDE.md", _render_user_claude_md())

    # Merge agent-os settings into existing settings.json rather than replace,
    # so plugin-installed hooks and keys are preserved across syncs.
    settings_path = claude_root / "settings.json"
    agent_os = _agent_os_settings()
    if settings_path.exists():
        try:
            existing = json.loads(settings_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            existing = {}
    else:
        existing = {}
    merged = _merge_claude_settings(existing, agent_os)
    _write_text(settings_path, json.dumps(merged, indent=2) + "\n")

    for agent_file in (REPO_ROOT / "core" / "agents").glob("*.md"):
        _copy_file(agent_file, claude_root / "agents" / agent_file.name)

    for skill_dir in _managed_skills():
        _copy_tree(skill_dir, claude_root / "skills" / skill_dir.name)
        _copy_tree(skill_dir, cursor_root / skill_dir.name)
        _copy_tree(skill_dir, codex_root / skill_dir.name)

    hermes_synced = _sync_hermes_runtime()

    print("Synced user runtime:")
    print(f"  - Claude: {claude_root}")
    print(f"  - Cursor skills: {cursor_root}")
    print(f"  - Codex skills: {codex_root}")
    if hermes_synced:
        print(f"  - Hermes: {HOME / '.hermes'}")


def _list_runtime() -> None:
    claude_root = HOME / ".claude"

    print("=== Agents ===")
    agents_dir = claude_root / "agents"
    if agents_dir.exists():
        for f in sorted(agents_dir.glob("*.md")):
            print(f"  {f.stem}")
    else:
        print("  (none)")

    print("\n=== Skills ===")
    skills_dir = claude_root / "skills"
    managed = {p.name for p in _managed_skills()}
    if skills_dir.exists():
        for d in sorted(skills_dir.iterdir()):
            if d.is_dir():
                tag = " [agent-os]" if d.name in managed else " [external]"
                print(f"  {d.name}{tag}")
    else:
        print("  (none)")

    print("\n=== Plugins ===")
    installed_json = claude_root / "plugins" / "installed_plugins.json"
    if installed_json.exists():
        data = json.loads(installed_json.read_text(encoding="utf-8"))
        for name in sorted(data.get("plugins", {}).keys()):
            print(f"  {name}")
    else:
        print("  (none)")

    print("\n=== Hooks (global settings.json) ===")
    settings_path = claude_root / "settings.json"
    if settings_path.exists():
        settings = json.loads(settings_path.read_text(encoding="utf-8"))
        for event, entries in settings.get("hooks", {}).items():
            for entry in entries:
                matcher = entry.get("matcher", "*")
                for h in entry.get("hooks", []):
                    cmd = h.get("command", "")
                    short = cmd.split("/")[-1] if "/" in cmd else cmd
                    print(f"  {event} [{matcher}] → {short}")


def _private_skill_source(name: str) -> Path:
    return REPO_ROOT / "skills" / "private" / name


def _private_skill_install_path(name: str, tool: str) -> Path:
    if tool != "claude":
        raise ValueError(f"unsupported private skill tool: {tool}")
    return HOME / ".claude" / "skills" / name


def _private_skill(action: str, name: str, tool: str) -> int:
    if tool != "claude":
        print(f"Private skills currently support only Claude. Unsupported tool: {tool}", file=sys.stderr)
        return 1

    source = _private_skill_source(name)
    install_path = _private_skill_install_path(name, tool)
    source_skill = source / "SKILL.md"
    installed = install_path.exists()

    if action == "status":
        print(f"Private skill: {name}")
        print(f"Tool: {tool}")
        print(f"Source: {source}")
        print(f"Install path: {install_path}")
        print(f"Source status: {'present' if source_skill.exists() else 'missing SKILL.md'}")
        print(f"Installed: {'yes' if installed else 'no'}")
        return 0

    if not source_skill.exists():
        print(f"Private skill source missing: {source_skill}", file=sys.stderr)
        return 1

    if action == "enable":
        if install_path.exists():
            shutil.rmtree(install_path)
        _copy_tree(source, install_path)
        print(f"Enabled private skill '{name}' for {tool}: {install_path}")
        return 0

    if action == "disable":
        if install_path.exists():
            shutil.rmtree(install_path)
            print(f"Disabled private skill '{name}' for {tool}: removed {install_path}")
        else:
            print(f"Private skill '{name}' is already absent for {tool}: {install_path}")
        return 0

    print(f"Unsupported private-skill action: {action}", file=sys.stderr)
    return 1


def _doctor() -> int:
    failures: list[str] = []
    print("Agent OS doctor")
    print(f"Repo root: {REPO_ROOT}")
    print(f"Expected Conda root: {CONDA_ROOT}")

    conda_bin = CONDA_ROOT / "bin" / "conda"
    if not conda_bin.exists():
        failures.append(f"missing conda binary at {conda_bin}")
    else:
        print(f"[ok] conda binary: {conda_bin}")

    try:
        envs = _run([str(conda_bin), "info", "--envs"]).stdout
        if re.search(r"^base\s+", envs, re.MULTILINE):
            print("[ok] conda base environment exists")
        else:
            failures.append("conda base environment not found")
    except subprocess.CalledProcessError as exc:
        failures.append(f"failed to inspect conda envs: {exc}")

    try:
        probe = _run(
            [
                str(conda_bin),
                "run",
                "-n",
                "base",
                "python",
                "-c",
                "import json,sys; print(json.dumps({'executable': sys.executable, 'prefix': sys.prefix}))",
            ]
        ).stdout.strip()
        if probe:
            payload = json.loads(probe.splitlines()[-1])
            executable = payload["executable"]
            prefix = payload["prefix"]
            if EXPECTED_BASE_PREFIX not in executable or EXPECTED_BASE_PREFIX not in prefix:
                failures.append(
                    f"conda base python did not resolve under {EXPECTED_BASE_PREFIX}: executable={executable} prefix={prefix}"
                )
            else:
                print(f"[ok] conda base python: {executable}")
        else:
            failures.append("conda run probe returned no output")
    except (subprocess.CalledProcessError, json.JSONDecodeError) as exc:
        failures.append(f"failed to run conda base python probe: {exc}")

    for tool in ["claude", "cursor", "git", "jq"]:
        if _command_exists(tool):
            print(f"[ok] tool available: {tool}")
        else:
            failures.append(f"missing tool: {tool}")

    optional_tools = ["tmux", "gh", "codex"]
    for tool in optional_tools:
        state = "present" if _command_exists(tool) else "not installed"
        print(f"[info] optional tool {tool}: {state}")

    if failures:
        print("\nDoctor failed:")
        for item in failures:
            print(f"  - {item}")
        return 1

    print("\nDoctor passed.")
    return 0


def _current_repo_root(cwd: Path) -> Path:
    try:
        output = _run(["git", "rev-parse", "--show-toplevel"], cwd=cwd).stdout.strip()
    except subprocess.CalledProcessError:
        return cwd.resolve()
    return Path(output)


def _resolve_bootstrap_target(path_arg: str) -> Path:
    candidate = Path(path_arg).expanduser()
    if path_arg == ".":
        return _current_repo_root(Path.cwd())
    return candidate.resolve()


def _worktree(task_type: str, task_name: list[str], base_ref: str | None, cwd: Path) -> int:
    repo_root = _current_repo_root(cwd)
    if not (repo_root / ".git").exists():
        print(f"Not a git repository: {repo_root}", file=sys.stderr)
        return 1

    slug = re.sub(r"[^a-z0-9]+", "-", " ".join(task_name).lower()).strip("-")
    if not slug:
        print("Unable to derive worktree slug.", file=sys.stderr)
        return 1

    branch_name = f"{task_type}/{slug}"
    parent_dir = repo_root.parent
    worktree_path = parent_dir / f"{repo_root.name}__{task_type}-{slug}"

    if not base_ref:
        base_ref = _run(["git", "rev-parse", "--abbrev-ref", "HEAD"], cwd=repo_root).stdout.strip()

    branch_exists = subprocess.run(
        ["git", "show-ref", "--verify", "--quiet", f"refs/heads/{branch_name}"],
        cwd=repo_root,
        check=False,
        capture_output=True,
        text=True,
    ).returncode == 0

    if branch_exists:
        _run(["git", "worktree", "add", str(worktree_path), branch_name], cwd=repo_root, capture_output=False)
    else:
        _run(
            ["git", "worktree", "add", "-b", branch_name, str(worktree_path), base_ref],
            cwd=repo_root,
            capture_output=False,
        )

    print(f"Created worktree: {worktree_path}")
    print(f"Branch: {branch_name}")
    return 0


def _start(tool: str, cwd: Path) -> int:
    if tool == "claude":
        os.execvp("claude", ["claude"])
    if tool == "cursor":
        os.execvp("cursor", ["cursor", str(cwd)])
    if tool == "codex":
        if _command_exists("codex"):
            os.execvp("codex", ["codex"])
        print("Codex CLI is not installed on PATH. Use Codex where available and rely on AGENTS.md plus synced skills.")
        return 1
    print(f"Unsupported tool: {tool}", file=sys.stderr)
    return 1


def _validate_manifest() -> int:
    """Check that every skill declared in runtime_manifest.json has a SKILL.md on disk.

    Also checks for the reverse: skill directories that exist but are not in the manifest.
    Returns 0 if clean, 1 if any issues found.
    """
    failures: list[str] = []
    warnings: list[str] = []

    all_declared = RUNTIME_MANIFEST["vendor_skills"] + RUNTIME_MANIFEST["custom_skills"]

    # Forward check: declared → file exists
    for bucket in ("vendor", "custom"):
        key = f"{bucket}_skills"
        for name in RUNTIME_MANIFEST[key]:
            skill_md = REPO_ROOT / "skills" / bucket / name / "SKILL.md"
            if not skill_md.exists():
                failures.append(f"[{bucket}] '{name}' declared in manifest but SKILL.md not found at {skill_md}")
            else:
                print(f"[ok] [{bucket}] {name}")

    # Reverse check: directories that exist but are not declared
    for bucket in ("vendor", "custom"):
        bucket_dir = REPO_ROOT / "skills" / bucket
        if not bucket_dir.exists():
            continue
        for skill_dir in sorted(bucket_dir.iterdir()):
            if skill_dir.is_dir() and skill_dir.name not in all_declared:
                warnings.append(f"[{bucket}] '{skill_dir.name}' directory exists but is not in manifest")

    # Agent check: every .md in core/agents/ is a real file
    agents_dir = REPO_ROOT / "core" / "agents"
    if agents_dir.exists():
        for f in sorted(agents_dir.glob("*.md")):
            print(f"[ok] [agent] {f.stem}")
    else:
        failures.append("core/agents/ directory missing")

    if warnings:
        print("\nWarnings:")
        for w in warnings:
            print(f"  ! {w}")

    if failures:
        print("\nValidation failed:")
        for f in failures:
            print(f"  x {f}")
        return 1

    print("\nValidation passed.")
    return 0


def _update() -> int:
    """Pull the latest agent-os from its git remote."""
    if not (REPO_ROOT / ".git").exists():
        print("agent-os repo has no .git directory — cannot update.", file=sys.stderr)
        return 1
    try:
        result = _run(["git", "pull", "--ff-only"], cwd=REPO_ROOT, capture_output=False)
        return result.returncode
    except subprocess.CalledProcessError as exc:
        print(f"Update failed: {exc}", file=sys.stderr)
        return 1


def _sync_hermes_runtime() -> bool:
    """Sync skills and operator context to Hermes if installed.

    Returns True if Hermes was found and synced, False if not installed.
    """
    hermes_root = HOME / ".hermes"
    if not hermes_root.exists():
        return False

    # Skills — Hermes uses agentskills.io format (same as our SKILL.md layout)
    skills_dst = hermes_root / "skills"
    for skill_dir in _managed_skills():
        _copy_tree(skill_dir, skills_dst / skill_dir.name)

    # Operator context — write a composite markdown file the user can load
    # from SOUL.md or reference manually.
    operator_md = hermes_root / "OPERATOR.md"
    sections: list[str] = [
        "# Operator Context\n\n"
        "Generated by `agent-os sync`. "
        "Edit sources in `~/agent-os/core/memory/global/`.\n\n"
    ]
    for mem_file in [
        REPO_ROOT / "core" / "memory" / "global" / "overview.md",
        REPO_ROOT / "core" / "memory" / "global" / "operator_profile.md",
        REPO_ROOT / "core" / "memory" / "global" / "workflow_policy.md",
    ]:
        if mem_file.exists():
            sections.append(mem_file.read_text(encoding="utf-8").rstrip() + "\n\n")
    _write_text(operator_md, "".join(sections))

    return True


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Agent OS cross-tool runtime manager")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("init", help="Bootstrap personal memory files from *.example.md templates")
    sub.add_parser("doctor", help="Verify Conda base and tool runtime wiring")
    sub.add_parser("sync", help="Sync managed runtime assets into Claude, Codex, Cursor, and Hermes")
    sub.add_parser("update", help="Pull the latest agent-os from git")
    sub.add_parser("list", help="Show installed agents, skills, plugins, and active hooks")
    sub.add_parser("validate", help="Check manifest integrity — every declared skill must have a SKILL.md")

    bootstrap = sub.add_parser("bootstrap", help="Bootstrap the standard project scaffold")
    bootstrap.add_argument("path", nargs="?", default=".")

    new_project = sub.add_parser("new-project", help="Alias for bootstrap — scaffold a new project")
    new_project.add_argument("path", nargs="?", default=".")

    worktree = sub.add_parser("worktree", help="Create a git worktree for a bounded task")
    worktree.add_argument("task_type")
    worktree.add_argument("task_name", nargs="+")
    worktree.add_argument("--base", dest="base_ref")

    private_skill = sub.add_parser("private-skill", help="Enable or disable a private experimental skill")
    private_skill.add_argument("action", choices=["enable", "disable", "status"])
    private_skill.add_argument("name")
    private_skill.add_argument("--tool", default="claude")

    start = sub.add_parser("start", help="Start the preferred agent surface")
    start.add_argument("tool", nargs="?", default="claude", choices=["claude", "cursor", "codex"])

    return parser


def main(argv: Iterable[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(list(argv) if argv is not None else None)

    if args.command == "init":
        return _init_memory()
    if args.command == "doctor":
        return _doctor()
    if args.command == "sync":
        _sync_user_runtime()
        return 0
    if args.command == "update":
        return _update()
    if args.command == "list":
        _list_runtime()
        return 0
    if args.command == "validate":
        return _validate_manifest()
    if args.command in ("bootstrap", "new-project"):
        _bootstrap_project(_resolve_bootstrap_target(args.path))
        return 0
    if args.command == "worktree":
        return _worktree(args.task_type, args.task_name, args.base_ref, Path.cwd())
    if args.command == "private-skill":
        return _private_skill(args.action, args.name, args.tool)
    if args.command == "start":
        return _start(args.tool, Path.cwd())
    parser.error(f"unsupported command: {args.command}")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
